import type { AuthorSeed } from "./types"

export const AUTHOR_SEED = [
  { openLibraryAuthorKey: "OL21594A", name: "Jane Austen" },
  { openLibraryAuthorKey: "OL20187A", name: "Harper Lee" },
  { openLibraryAuthorKey: "OL26176A", name: "F. Scott Fitzgerald" },
  { openLibraryAuthorKey: "OL23919A", name: "Herman Melville" },
  { openLibraryAuthorKey: "OL18319A", name: "Emily Brontë" },
  { openLibraryAuthorKey: "OL2162284A", name: "Charlotte Brontë" },
  { openLibraryAuthorKey: "OL22220A", name: "Fyodor Dostoyevsky" },
  { openLibraryAuthorKey: "OL39505A", name: "J. D. Salinger" },
  { openLibraryAuthorKey: "OL34221A", name: "Toni Morrison" },
  { openLibraryAuthorKey: "OL42774A", name: "Ralph Ellison" },
  { openLibraryAuthorKey: "OL234662A", name: "Chinua Achebe" },
  { openLibraryAuthorKey: "OL39491A", name: "Virginia Woolf" },
  { openLibraryAuthorKey: "OL26320A", name: "J.R.R. Tolkien" },
  { openLibraryAuthorKey: "OL234664A", name: "C. S. Lewis" },
  { openLibraryAuthorKey: "OL25712A", name: "Ursula K. Le Guin" },
  { openLibraryAuthorKey: "OL2676165A", name: "George R. R. Martin" },
  { openLibraryAuthorKey: "OL1394221A", name: "Patrick Rothfuss" },
  { openLibraryAuthorKey: "OL1394222A", name: "Brandon Sanderson" },
  { openLibraryAuthorKey: "OL26737A", name: "Neil Gaiman" },
  { openLibraryAuthorKey: "OL27320A", name: "Terry Pratchett" },
  { openLibraryAuthorKey: "OL23919C", name: "J. K. Rowling" },
  { openLibraryAuthorKey: "OL1394224A", name: "Scott Lynch" },
  { openLibraryAuthorKey: "OL1394223A", name: "Joe Abercrombie" },
  { openLibraryAuthorKey: "OL118077A", name: "George Orwell" },
  { openLibraryAuthorKey: "OL189047A", name: "Frank Herbert" },
  { openLibraryAuthorKey: "OL31247A", name: "William Gibson" },
  { openLibraryAuthorKey: "OL161167A", name: "Isaac Asimov" },
  { openLibraryAuthorKey: "OL52266A", name: "Aldous Huxley" },
  { openLibraryAuthorKey: "OL2622896A", name: "Dan Simmons" },
  { openLibraryAuthorKey: "OL2676166A", name: "Neal Stephenson" },
  { openLibraryAuthorKey: "OL7115215A", name: "Andy Weir" },
  { openLibraryAuthorKey: "OL448910A", name: "Philip K. Dick" },
  { openLibraryAuthorKey: "OL20187B", name: "Douglas Adams" },
  { openLibraryAuthorKey: "OL22018A", name: "Ray Bradbury" },
  { openLibraryAuthorKey: "OL27695A", name: "Mary Shelley" },
  { openLibraryAuthorKey: "OL246338A", name: "Bram Stoker" },
  { openLibraryAuthorKey: "OL21582A", name: "Stephen King" },
  { openLibraryAuthorKey: "OL2650461A", name: "Shirley Jackson" },
  { openLibraryAuthorKey: "OL22020A", name: "William Peter Blatty" },
  { openLibraryAuthorKey: "OL2641540A", name: "Anne Rice" },
  { openLibraryAuthorKey: "OL22021A", name: "H. P. Lovecraft" },
  { openLibraryAuthorKey: "OL6932577A", name: "Silvia Moreno-Garcia" },
  { openLibraryAuthorKey: "OL6932578A", name: "Josh Malerman" },
  { openLibraryAuthorKey: "OLSEEDA001A", name: "Agatha Christie" },
  { openLibraryAuthorKey: "OLSEEDA002A", name: "Arthur Conan Doyle" },
  { openLibraryAuthorKey: "OLSEEDA003A", name: "Gillian Flynn" },
  { openLibraryAuthorKey: "OLSEEDA004A", name: "Tana French" },
  { openLibraryAuthorKey: "OLSEEDA005A", name: "Raymond Chandler" },
  { openLibraryAuthorKey: "OLSEEDA006A", name: "Dashiell Hammett" },
  { openLibraryAuthorKey: "OLSEEDA007A", name: "Paula Hawkins" },
  { openLibraryAuthorKey: "OLSEEDA008A", name: "John le Carré" },
  { openLibraryAuthorKey: "OLSEEDA009A", name: "Louise Penny" },
  { openLibraryAuthorKey: "OLSEEDA010A", name: "Walter Mosley" },
  { openLibraryAuthorKey: "OLSEEDA011A", name: "Kate Atkinson" },
  { openLibraryAuthorKey: "OLSEEDA012A", name: "Donna Tartt" },
  { openLibraryAuthorKey: "OLSEEDA014A", name: "Nora Roberts" },
  { openLibraryAuthorKey: "OLSEEDA015A", name: "Emily Henry" },
  { openLibraryAuthorKey: "OLSEEDA016A", name: "Casey McQuiston" },
  { openLibraryAuthorKey: "OLSEEDA017A", name: "Colleen Hoover" },
  { openLibraryAuthorKey: "OLSEEDA018A", name: "Helen Hoang" },
  { openLibraryAuthorKey: "OLSEEDA019A", name: "Julia Quinn" },
  { openLibraryAuthorKey: "OLSEEDA020A", name: "Rebecca Yarros" },
  { openLibraryAuthorKey: "OLSEEDA021A", name: "Ali Hazelwood" },
  { openLibraryAuthorKey: "OLSEEDA022A", name: "Taylor Jenkins Reid" },
  { openLibraryAuthorKey: "OLSEEDA023A", name: "Rainbow Rowell" },
  { openLibraryAuthorKey: "OLSEEDA024A", name: "Diana Gabaldon" },
  { openLibraryAuthorKey: "OLSEEDA025A", name: "Hilary Mantel" },
  { openLibraryAuthorKey: "OLSEEDA026A", name: "Ken Follett" },
  { openLibraryAuthorKey: "OLSEEDA027A", name: "Anthony Doerr" },
  { openLibraryAuthorKey: "OLSEEDA028A", name: "Kristin Hannah" },
  { openLibraryAuthorKey: "OLSEEDA029A", name: "Madeline Miller" },
  { openLibraryAuthorKey: "OLSEEDA030A", name: "Colson Whitehead" },
  { openLibraryAuthorKey: "OLSEEDA031A", name: "Geraldine Brooks" },
  { openLibraryAuthorKey: "OLSEEDA032A", name: "Min Jin Lee" },
  { openLibraryAuthorKey: "OLSEEDA033A", name: "Lisa See" },
  { openLibraryAuthorKey: "OLSEEDA034A", name: "Yaa Gyasi" },
  { openLibraryAuthorKey: "OLSEEDA035A", name: "Maggie O'Farrell" },
  { openLibraryAuthorKey: "OLSEEDA036A", name: "James Clavell" },
  { openLibraryAuthorKey: "OLSEEDA037A", name: "John Green" },
  { openLibraryAuthorKey: "OLSEEDA038A", name: "Suzanne Collins" },
  { openLibraryAuthorKey: "OLSEEDA039A", name: "Veronica Roth" },
  { openLibraryAuthorKey: "OLSEEDA040A", name: "Angie Thomas" },
  { openLibraryAuthorKey: "OLSEEDA041A", name: "S. E. Hinton" },
  { openLibraryAuthorKey: "OLSEEDA042A", name: "Cassandra Clare" },
  { openLibraryAuthorKey: "OLSEEDA043A", name: "Leigh Bardugo" },
  { openLibraryAuthorKey: "OLSEEDA044A", name: "Holly Black" },
  { openLibraryAuthorKey: "OLSEEDA045A", name: "Jason Reynolds" },
  { openLibraryAuthorKey: "OLSEEDA046A", name: "Nicola Yoon" },
  { openLibraryAuthorKey: "OLSEEDA047A", name: "E. Lockhart" },
  { openLibraryAuthorKey: "OLSEEDA048A", name: "Sarah J. Maas" },
  { openLibraryAuthorKey: "OLSEEDA049A", name: "Roald Dahl" },
  { openLibraryAuthorKey: "OLSEEDA050A", name: "E. B. White" },
  { openLibraryAuthorKey: "OLSEEDA051A", name: "Maurice Sendak" },
  { openLibraryAuthorKey: "OLSEEDA052A", name: "Dr. Seuss" },
  { openLibraryAuthorKey: "OLSEEDA053A", name: "Beverly Cleary" },
  { openLibraryAuthorKey: "OLSEEDA054A", name: "Kate DiCamillo" },
  { openLibraryAuthorKey: "OLSEEDA055A", name: "Rick Riordan" },
  { openLibraryAuthorKey: "OLSEEDA056A", name: "L. M. Montgomery" },
  { openLibraryAuthorKey: "OLSEEDA057A", name: "A. A. Milne" },
  { openLibraryAuthorKey: "OLSEEDA058A", name: "Frances Hodgson Burnett" },
  { openLibraryAuthorKey: "OLSEEDA059A", name: "Lewis Carroll" },
  { openLibraryAuthorKey: "OLSEEDA060A", name: "Eric Carle" },
  { openLibraryAuthorKey: "OLSEEDA061A", name: "Alan Moore" },
  { openLibraryAuthorKey: "OLSEEDA062A", name: "Art Spiegelman" },
  { openLibraryAuthorKey: "OLSEEDA063A", name: "Frank Miller" },
  { openLibraryAuthorKey: "OLSEEDA064A", name: "Marjane Satrapi" },
  { openLibraryAuthorKey: "OLSEEDA066A", name: "Jeff Lemire" },
  { openLibraryAuthorKey: "OLSEEDA067A", name: "Raina Telgemeier" },
  { openLibraryAuthorKey: "OLSEEDA068A", name: "Brian K. Vaughan" },
  { openLibraryAuthorKey: "OLSEEDA069A", name: "Alison Bechdel" },
  { openLibraryAuthorKey: "OLSEEDA070A", name: "Gene Luen Yang" },
  { openLibraryAuthorKey: "OLSEEDA071A", name: "Katsuhiro Otomo" },
  { openLibraryAuthorKey: "OLSEEDA072A", name: "Hajime Isayama" },
  { openLibraryAuthorKey: "OLSEEDA073A", name: "Raymond Carver" },
  { openLibraryAuthorKey: "OLSEEDA074A", name: "Alice Munro" },
  { openLibraryAuthorKey: "OLSEEDA075A", name: "Jhumpa Lahiri" },
  { openLibraryAuthorKey: "OLSEEDA076A", name: "George Saunders" },
  { openLibraryAuthorKey: "OLSEEDA077A", name: "Flannery O'Connor" },
  { openLibraryAuthorKey: "OLSEEDA078A", name: "James Joyce" },
  { openLibraryAuthorKey: "OLSEEDA079A", name: "Ted Chiang" },
  { openLibraryAuthorKey: "OLSEEDA080A", name: "Karen Russell" },
  { openLibraryAuthorKey: "OLSEEDA081A", name: "Ottessa Moshfegh" },
  { openLibraryAuthorKey: "OLSEEDA082A", name: "Carmen Maria Machado" },
  { openLibraryAuthorKey: "OLSEEDA083A", name: "Edgar Allan Poe" },
  { openLibraryAuthorKey: "OLSEEDA084A", name: "Anton Chekhov" },
  { openLibraryAuthorKey: "OLSEEDA085A", name: "Larry McMurtry" },
  { openLibraryAuthorKey: "OLSEEDA086A", name: "Cormac McCarthy" },
  { openLibraryAuthorKey: "OLSEEDA087A", name: "Charles Portis" },
  { openLibraryAuthorKey: "OLSEEDA088A", name: "Zane Grey" },
  { openLibraryAuthorKey: "OLSEEDA089A", name: "Louis L'Amour" },
  { openLibraryAuthorKey: "OLSEEDA090A", name: "Elmer Kelton" },
  { openLibraryAuthorKey: "OLSEEDA091A", name: "Thomas Berger" },
  { openLibraryAuthorKey: "OLSEEDA092A", name: "Glendon Swarthout" },
  { openLibraryAuthorKey: "OLSEEDA093A", name: "Jack Schaefer" },
  { openLibraryAuthorKey: "OLSEEDA094A", name: "Walter Van Tilburg Clark" },
  { openLibraryAuthorKey: "OLSEEDA095A", name: "Oakley Hall" },
  { openLibraryAuthorKey: "OLSEEDA096A", name: "Anna North" },
  { openLibraryAuthorKey: "OLSEEDA097A", name: "Emily Dickinson" },
  { openLibraryAuthorKey: "OLSEEDA098A", name: "Walt Whitman" },
  { openLibraryAuthorKey: "OLSEEDA099A", name: "Maya Angelou" },
  { openLibraryAuthorKey: "OLSEEDA100A", name: "Mary Oliver" },
  { openLibraryAuthorKey: "OLSEEDA101A", name: "T. S. Eliot" },
  { openLibraryAuthorKey: "OLSEEDA102A", name: "Sylvia Plath" },
  { openLibraryAuthorKey: "OLSEEDA103A", name: "Robert Frost" },
  { openLibraryAuthorKey: "OLSEEDA104A", name: "Langston Hughes" },
  { openLibraryAuthorKey: "OLSEEDA105A", name: "Ocean Vuong" },
  { openLibraryAuthorKey: "OLSEEDA106A", name: "Danez Smith" },
  { openLibraryAuthorKey: "OLSEEDA107A", name: "Rumi" },
  { openLibraryAuthorKey: "OLSEEDA108A", name: "Seamus Heaney" },
  { openLibraryAuthorKey: "OLSEEDA109A", name: "William Shakespeare" },
  { openLibraryAuthorKey: "OLSEEDA110A", name: "Arthur Miller" },
  { openLibraryAuthorKey: "OLSEEDA111A", name: "Tennessee Williams" },
  { openLibraryAuthorKey: "OLSEEDA112A", name: "Lorraine Hansberry" },
  { openLibraryAuthorKey: "OLSEEDA113A", name: "August Wilson" },
  { openLibraryAuthorKey: "OLSEEDA114A", name: "Sophocles" },
  { openLibraryAuthorKey: "OLSEEDA115A", name: "Samuel Beckett" },
  { openLibraryAuthorKey: "OLSEEDA116A", name: "Henrik Ibsen" },
  { openLibraryAuthorKey: "OLSEEDA118A", name: "Lin-Manuel Miranda" },
  { openLibraryAuthorKey: "OLSEEDA119A", name: "Tom Stoppard" },
  { openLibraryAuthorKey: "OLSEEDA120A", name: "Oscar Wilde" },
  { openLibraryAuthorKey: "OLSEEDA121A", name: "Yuval Noah Harari" },
  { openLibraryAuthorKey: "OLSEEDA122A", name: "Howard Zinn" },
  { openLibraryAuthorKey: "OLSEEDA123A", name: "Doris Kearns Goodwin" },
  { openLibraryAuthorKey: "OLSEEDA124A", name: "Erik Larson" },
  { openLibraryAuthorKey: "OLSEEDA125A", name: "David McCullough" },
  { openLibraryAuthorKey: "OLSEEDA126A", name: "Barbara W. Tuchman" },
  { openLibraryAuthorKey: "OLSEEDA127A", name: "Jill Lepore" },
  { openLibraryAuthorKey: "OLSEEDA128A", name: "Ron Chernow" },
  { openLibraryAuthorKey: "OLSEEDA129A", name: "Isabel Wilkerson" },
  { openLibraryAuthorKey: "OLSEEDA130A", name: "Timothy Snyder" },
  { openLibraryAuthorKey: "OLSEEDA131A", name: "Mary Beard" },
  { openLibraryAuthorKey: "OLSEEDA132A", name: "Tony Judt" },
  { openLibraryAuthorKey: "OLSEEDA133A", name: "Michelle Obama" },
  { openLibraryAuthorKey: "OLSEEDA134A", name: "Barack Obama" },
  { openLibraryAuthorKey: "OLSEEDA135A", name: "Walter Isaacson" },
  { openLibraryAuthorKey: "OLSEEDA136A", name: "Robert Caro" },
  { openLibraryAuthorKey: "OLSEEDA137A", name: "Anne Frank" },
  { openLibraryAuthorKey: "OLSEEDA138A", name: "Tara Westover" },
  { openLibraryAuthorKey: "OLSEEDA139A", name: "Jeannette Walls" },
  { openLibraryAuthorKey: "OLSEEDA140A", name: "Trevor Noah" },
  { openLibraryAuthorKey: "OLSEEDA141A", name: "Michelle Zauner" },
  { openLibraryAuthorKey: "OLSEEDA142A", name: "Patti Smith" },
  { openLibraryAuthorKey: "OLSEEDA144A", name: "Sonia Sotomayor" },
  { openLibraryAuthorKey: "OLSEEDA145A", name: "Hannah Arendt" },
  { openLibraryAuthorKey: "OLSEEDA146A", name: "Thomas Paine" },
  { openLibraryAuthorKey: "OLSEEDA147A", name: "Niccolò Machiavelli" },
  { openLibraryAuthorKey: "OLSEEDA148A", name: "Alexis de Tocqueville" },
  { openLibraryAuthorKey: "OLSEEDA149A", name: "James Baldwin" },
  { openLibraryAuthorKey: "OLSEEDA150A", name: "Ta-Nehisi Coates" },
  { openLibraryAuthorKey: "OLSEEDA151A", name: "Michelle Alexander" },
  { openLibraryAuthorKey: "OLSEEDA152A", name: "Noam Chomsky" },
  { openLibraryAuthorKey: "OLSEEDA153A", name: "Francis Fukuyama" },
  { openLibraryAuthorKey: "OLSEEDA154A", name: "Anne Applebaum" },
  { openLibraryAuthorKey: "OLSEEDA155A", name: "Ezra Klein" },
  { openLibraryAuthorKey: "OLSEEDA156A", name: "Ibram X. Kendi" },
  { openLibraryAuthorKey: "OLSEEDA158A", name: "Karen Armstrong" },
  { openLibraryAuthorKey: "OLSEEDA159A", name: "Thich Nhat Hanh" },
  { openLibraryAuthorKey: "OLSEEDA160A", name: "Bart D. Ehrman" },
  { openLibraryAuthorKey: "OLSEEDA161A", name: "Reza Aslan" },
  { openLibraryAuthorKey: "OLSEEDA162A", name: "Elaine Pagels" },
  { openLibraryAuthorKey: "OLSEEDA163A", name: "Augustine of Hippo" },
  { openLibraryAuthorKey: "OLSEEDA164A", name: "The Dalai Lama" },
  { openLibraryAuthorKey: "OLSEEDA165A", name: "Thomas Merton" },
  { openLibraryAuthorKey: "OLSEEDA166A", name: "Rabbi Jonathan Sacks" },
  { openLibraryAuthorKey: "OLSEEDA167A", name: "Pema Chödrön" },
  { openLibraryAuthorKey: "OLSEEDA168A", name: "Marcus J. Borg" },
  { openLibraryAuthorKey: "OLSEEDA169A", name: "Carl Sagan" },
  { openLibraryAuthorKey: "OLSEEDA170A", name: "Stephen Hawking" },
  { openLibraryAuthorKey: "OLSEEDA171A", name: "Richard Dawkins" },
  { openLibraryAuthorKey: "OLSEEDA172A", name: "Neil deGrasse Tyson" },
  { openLibraryAuthorKey: "OLSEEDA173A", name: "Mary Roach" },
  { openLibraryAuthorKey: "OLSEEDA174A", name: "Bill Bryson" },
  { openLibraryAuthorKey: "OLSEEDA175A", name: "Rachel Carson" },
  { openLibraryAuthorKey: "OLSEEDA176A", name: "Oliver Sacks" },
  { openLibraryAuthorKey: "OLSEEDA177A", name: "Siddhartha Mukherjee" },
  { openLibraryAuthorKey: "OLSEEDA178A", name: "James Gleick" },
  { openLibraryAuthorKey: "OLSEEDA179A", name: "Brian Greene" },
  { openLibraryAuthorKey: "OLSEEDA180A", name: "Ed Yong" },
  { openLibraryAuthorKey: "OLSEEDA181A", name: "James Clear" },
  { openLibraryAuthorKey: "OLSEEDA182A", name: "Daniel Kahneman" },
  { openLibraryAuthorKey: "OLSEEDA183A", name: "Eric Ries" },
  { openLibraryAuthorKey: "OLSEEDA184A", name: "Ben Horowitz" },
  { openLibraryAuthorKey: "OLSEEDA185A", name: "Jim Collins" },
  { openLibraryAuthorKey: "OLSEEDA186A", name: "Peter Thiel" },
  { openLibraryAuthorKey: "OLSEEDA187A", name: "Clayton M. Christensen" },
  { openLibraryAuthorKey: "OLSEEDA188A", name: "Nassim Nicholas Taleb" },
  { openLibraryAuthorKey: "OLSEEDA189A", name: "Adam Grant" },
  { openLibraryAuthorKey: "OLSEEDA190A", name: "Simon Sinek" },
  { openLibraryAuthorKey: "OLSEEDA191A", name: "Sheryl Sandberg" },
  { openLibraryAuthorKey: "OLSEEDA192A", name: "Michael Lewis" },
  { openLibraryAuthorKey: "OLSEEDA193A", name: "Plato" },
  { openLibraryAuthorKey: "OLSEEDA194A", name: "Marcus Aurelius" },
  { openLibraryAuthorKey: "OLSEEDA195A", name: "Friedrich Nietzsche" },
  { openLibraryAuthorKey: "OLSEEDA196A", name: "Simone de Beauvoir" },
  { openLibraryAuthorKey: "OLSEEDA197A", name: "Albert Camus" },
  { openLibraryAuthorKey: "OLSEEDA198A", name: "René Descartes" },
  { openLibraryAuthorKey: "OLSEEDA199A", name: "Immanuel Kant" },
  { openLibraryAuthorKey: "OLSEEDA200A", name: "Aristotle" },
  { openLibraryAuthorKey: "OLSEEDA201A", name: "Jean-Paul Sartre" },
  { openLibraryAuthorKey: "OLSEEDA202A", name: "Epictetus" },
  { openLibraryAuthorKey: "OLSEEDA203A", name: "Bertrand Russell" },
  { openLibraryAuthorKey: "OLSEEDA204A", name: "Susan Sontag" },
  { openLibraryAuthorKey: "OLSEEDA205A", name: "John Berger" },
  { openLibraryAuthorKey: "OLSEEDA207A", name: "Ernst Gombrich" },
  { openLibraryAuthorKey: "OLSEEDA208A", name: "David Hockney" },
  { openLibraryAuthorKey: "OLSEEDA209A", name: "Grayson Perry" },
  { openLibraryAuthorKey: "OLSEEDA210A", name: "Austin Kleon" },
  { openLibraryAuthorKey: "OLSEEDA211A", name: "Debbie Millman" },
  { openLibraryAuthorKey: "OLSEEDA212A", name: "Phaidon Editors" },
  { openLibraryAuthorKey: "OLSEEDA213A", name: "Hal Foster" },
  { openLibraryAuthorKey: "OLSEEDA214A", name: "Jerry Saltz" },
  { openLibraryAuthorKey: "OLSEEDA215A", name: "Sarah Thornton" },
  { openLibraryAuthorKey: "OLSEEDA216A", name: "Wassily Kandinsky" },
  { openLibraryAuthorKey: "OLSEEDA217A", name: "Alex Ross" },
  { openLibraryAuthorKey: "OLSEEDA218A", name: "Ted Gioia" },
  { openLibraryAuthorKey: "OLSEEDA219A", name: "Questlove" },
  { openLibraryAuthorKey: "OLSEEDA220A", name: "Kim Gordon" },
  { openLibraryAuthorKey: "OLSEEDA221A", name: "Bob Dylan" },
  { openLibraryAuthorKey: "OLSEEDA223A", name: "David Byrne" },
  { openLibraryAuthorKey: "OLSEEDA224A", name: "Greil Marcus" },
  { openLibraryAuthorKey: "OLSEEDA225A", name: "Hanif Abdurraqib" },
  { openLibraryAuthorKey: "OLSEEDA226A", name: "Liz Pelly" },
  { openLibraryAuthorKey: "OLSEEDA227A", name: "Alan Light" },
  { openLibraryAuthorKey: "OLSEEDA228A", name: "Rick Rubin" },
  { openLibraryAuthorKey: "OLSEEDA229A", name: "Bryan Stevenson" },
  { openLibraryAuthorKey: "OLSEEDA230A", name: "John Grisham" },
  { openLibraryAuthorKey: "OLSEEDA230B", name: "Scott Turow" },
  { openLibraryAuthorKey: "OLSEEDA231A", name: "Linda Greenhouse" },
  { openLibraryAuthorKey: "OLSEEDA232A", name: "Jeffrey Toobin" },
  { openLibraryAuthorKey: "OLSEEDA233A", name: "Lawrence Lessig" },
  { openLibraryAuthorKey: "OLSEEDA234A", name: "Richard A. Posner" },
  { openLibraryAuthorKey: "OLSEEDA235A", name: "Anthony Lewis" },
  { openLibraryAuthorKey: "OLSEEDA236A", name: "Emily Bazelon" },
  { openLibraryAuthorKey: "OLSEEDA237A", name: "Dahlia Lithwick" },
  { openLibraryAuthorKey: "OLSEEDA238A", name: "Noah Feldman" },
  { openLibraryAuthorKey: "OLSEEDA239A", name: "Akhil Reed Amar" },
  { openLibraryAuthorKey: "OLSEEDA240A", name: "Erwin Chemerinsky" },
  { openLibraryAuthorKey: "OLSEEDA241A", name: "Paulo Freire" },
  { openLibraryAuthorKey: "OLSEEDA242A", name: "bell hooks" },
  { openLibraryAuthorKey: "OLSEEDA243A", name: "John Dewey" },
  { openLibraryAuthorKey: "OLSEEDA244A", name: "Ken Robinson" },
  { openLibraryAuthorKey: "OLSEEDA245A", name: "Diane Ravitch" },
  { openLibraryAuthorKey: "OLSEEDA246A", name: "Carol S. Dweck" },
  { openLibraryAuthorKey: "OLSEEDA247A", name: "Angela Duckworth" },
  { openLibraryAuthorKey: "OLSEEDA248A", name: "Jonathan Kozol" },
  { openLibraryAuthorKey: "OLSEEDA249A", name: "Mike Rose" },
  { openLibraryAuthorKey: "OLSEEDA250A", name: "Lisa Delpit" },
  { openLibraryAuthorKey: "OLSEEDA252A", name: "Alfie Kohn" },
  { openLibraryAuthorKey: "OLSEEDA254A", name: "Paul Theroux" },
  { openLibraryAuthorKey: "OLSEEDA255A", name: "Cheryl Strayed" },
  { openLibraryAuthorKey: "OLSEEDA256A", name: "Elizabeth Gilbert" },
  { openLibraryAuthorKey: "OLSEEDA257A", name: "Bruce Chatwin" },
  { openLibraryAuthorKey: "OLSEEDA258A", name: "Pico Iyer" },
  { openLibraryAuthorKey: "OLSEEDA259A", name: "Anthony Bourdain" },
  { openLibraryAuthorKey: "OLSEEDA260A", name: "Rory Stewart" },
  { openLibraryAuthorKey: "OLSEEDA261A", name: "Jan Morris" },
  { openLibraryAuthorKey: "OLSEEDA262A", name: "Rebecca Solnit" },
  { openLibraryAuthorKey: "OLSEEDA263A", name: "Patrick Leigh Fermor" },
  { openLibraryAuthorKey: "OLSEEDA267A", name: "Cathy O'Neil" },
  { openLibraryAuthorKey: "OLSEEDA268A", name: "Shoshana Zuboff" },
  { openLibraryAuthorKey: "OLSEEDA269A", name: "James Bridle" },
  { openLibraryAuthorKey: "OLSEEDA270A", name: "Jaron Lanier" },
  { openLibraryAuthorKey: "OLSEEDA271A", name: "Tim Wu" },
  { openLibraryAuthorKey: "OLSEEDA272A", name: "Brian Merchant" },
  { openLibraryAuthorKey: "OLSEEDA273A", name: "Meredith Broussard" },
  { openLibraryAuthorKey: "OLSEEDA274A", name: "Kate Crawford" },
  { openLibraryAuthorKey: "OLSEEDA275A", name: "Cal Newport" },
  { openLibraryAuthorKey: "OLSEEDA276A", name: "Douglas Rushkoff" },
  { openLibraryAuthorKey: "OLSEEDA277A", name: "Samin Nosrat" },
  { openLibraryAuthorKey: "OLSEEDA278A", name: "Julia Child" },
  { openLibraryAuthorKey: "OLSEEDA279A", name: "Irma S. Rombauer" },
  { openLibraryAuthorKey: "OLSEEDA280A", name: "Yotam Ottolenghi" },
  { openLibraryAuthorKey: "OLSEEDA281A", name: "Alison Roman" },
  { openLibraryAuthorKey: "OLSEEDA282A", name: "Deb Perelman" },
  { openLibraryAuthorKey: "OLSEEDA283A", name: "J. Kenji López-Alt" },
  { openLibraryAuthorKey: "OLSEEDA285A", name: "Madhur Jaffrey" },
  { openLibraryAuthorKey: "OLSEEDA286A", name: "Ina Garten" },
  { openLibraryAuthorKey: "OLSEEDA287A", name: "Nigella Lawson" },
  { openLibraryAuthorKey: "OLSEEDA288A", name: "David Chang" },
  { openLibraryAuthorKey: "OLSEEDA289A", name: "John Feinstein" },
  { openLibraryAuthorKey: "OLSEEDA291A", name: "David Halberstam" },
  { openLibraryAuthorKey: "OLSEEDA292A", name: "Andre Agassi" },
  { openLibraryAuthorKey: "OLSEEDA293A", name: "Phil Knight" },
  { openLibraryAuthorKey: "OLSEEDA294A", name: "Buzz Bissinger" },
  { openLibraryAuthorKey: "OLSEEDA295A", name: "Laura Hillenbrand" },
  { openLibraryAuthorKey: "OLSEEDA296A", name: "Gay Talese" },
  { openLibraryAuthorKey: "OLSEEDA297A", name: "Bill Simmons" },
  { openLibraryAuthorKey: "OLSEEDA298A", name: "Wright Thompson" },
  { openLibraryAuthorKey: "OLSEEDA299A", name: "Dave Zirin" },
  { openLibraryAuthorKey: "OLSEEDA300A", name: "Kathrine Switzer" },
  { openLibraryAuthorKey: "OLSEEDA301A", name: "Joan Didion" },
  { openLibraryAuthorKey: "OLSEEDA303A", name: "David Foster Wallace" },
  { openLibraryAuthorKey: "OLSEEDA304A", name: "Zadie Smith" },
  { openLibraryAuthorKey: "OLSEEDA306A", name: "Audre Lorde" },
  { openLibraryAuthorKey: "OLSEEDA309A", name: "Roxane Gay" },
  { openLibraryAuthorKey: "OLSEEDA310A", name: "Jia Tolentino" },
  { openLibraryAuthorKey: "OLSEEDA311A", name: "Leslie Jamison" },
  { openLibraryAuthorKey: "OLSEEDA312A", name: "Hilton Als" },
  { openLibraryAuthorKey: "OLSEEDA264B", name: "Bess Kalb" },
  { openLibraryAuthorKey: "OLSEEDA266B", name: "Steven Levy" },
] as const satisfies readonly AuthorSeed[]
